@startuml
class PanelHelp {
- String fuente
+ JLabel correo
+ JButton HAtras
~ {static} String bHAtras
~ {static} String bHEnviar
+ void controlador(ActionListener)
}
class CtrChat {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class CtrJEmpleados {
~ VistaEasyJob vistaEasy
~ ConexionBD conex
+ void actionPerformed(ActionEvent)
}
class PanelJefe {
- String fuente
+ JButton VerEmpleados
+ ImagePanel imagenPanel
~ {static} String bVerEmpleados
~ {static} String bSolicitudes
~ {static} String bCerrarS
~ {static} String bConf
~ {static} String bChatJ
~ {static} String bHelpJ
~ ConexionBD conex
+ void controlador(ActionListener)
+ {static} byte[] toByteArray(BufferedImage,String)
}
class PanelJefe.ImagePanel {
- BufferedImage image
~ void setImage(BufferedImage)
# void paintComponent(Graphics)
}
class PanelCCContraseña {
- String fuente
~ JButton CContraseñaAtras
~ JPasswordField contraseñaAntigua
~ JLabel LcontraseñaAntigua
~ {static} String bCContraseñaAtras
~ {static} String bCContraseñaActualizar
~ ConexionBD conex
+ void controlador(ActionListener)
}
class CtrHSolicitud {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class CtrCCContraseña {
+ void actionPerformed(ActionEvent)
}
class CtrCambCorreo {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class ConexionBaseDatosJDBC {
- {static} ConexionBaseDatosJDBC instanciaInterfaz
~ PreparedStatement ps
~ ResultSet rs
- Connection conn
- boolean esJefe
+ {static} ConexionBaseDatosJDBC getInstance()
+ void introducirUsuario(Usuario)
+ boolean buscarUsuario(String,String)
+ boolean esOnoJefe()
+ List<Usuario> verUsuarios()
+ List<Mensaje> verMensajes()
+ List<Mensaje> verMensajesEnviados()
+ List<SolicitudHorario> verSolicitudes()
+ void eliminarSolicitud(int)
+ void añadirHorario(String,int[])
+ void añadirSolicitud(String,int[])
+ void cambiarHorario(String,int[])
+ void EnviarMensaje(String,String,String)
+ void BorrarMensaje(int)
+ boolean esOnoJefe(String)
+ void Ascender(String,boolean)
+ void eliminarUsuario(String)
+ void borrarHorario(String)
+ void borrarMensajes(String)
+ void borrarSolicitudHorario(String)
+ boolean ContrAntiguaCorrecta(String,String)
+ boolean CorreoAntiguoCorrecto(String,String)
+ boolean TelefAntiguoCorrecto(String,String)
+ void cambiarCorreo(String,String,String)
+ void cambiarContraseña(String,String,String)
+ void cambiarTelefono(String,String,String)
+ Horario horarioFavorito(String)
+ void anadirQR(byte[],String)
+ boolean tieneQR(String)
+ byte[] getQR(String)
+ boolean tieneFoto(String)
+ byte[] getFoto(String)
+ void anadirFoto(byte[],String)
}
class CtrlNuevoUsuario {
- ConexionBD conexionbd
- PanelRegistro panel
+ void actionPerformed(ActionEvent)
}
class CtrJSolicitud {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class CtrVerMensajes {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class PanelJVerEmpleados {
- String fuente
~ ConexionBD conex
- String[] usuarios
- JList<String> listaUsuarios
~ {static} String seleccionado
- int index
- DefaultListModel listModel
~ JButton borrar
~ {static} String bBorrar
~ {static} String bAscender
~ {static} String bJVE
+ void valueChanged(ListSelectionEvent)
+ void controlador(ActionListener)
}
class PanelEnviarMensajeDeveloper {
~ JButton enviar
~ {static} String bEnviar
~ {static} String bAtras
- JLabel destinatario
- JTextField destinatarioField
- JTextArea mensajeField
~ ConexionBD conex
+ void controlador(ActionListener)
}
class CtrEnviarMensajes {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class PanelFichar {
- String fuente
+ ImagePanel imagenPanel
+ ConexionBD conex
+ BufferedImage img
- JButton ficharAtras
- JLabel fichar
~ {static} String bFichar
~ {static} String bMFichar
~ {static} String bQR
+ void controlador(ActionListener)
+ void generarQR()
+ {static} byte[] toByteArray(BufferedImage,String)
}
class PanelFichar.ImagePanel {
- BufferedImage image
~ void setImage(BufferedImage)
# void paintComponent(Graphics)
}
class CtrFichar {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class PanelChat {
~ JButton enviarMensaje
- String fuente
~ {static} String ENVIARMENSAJE
~ {static} String MENSAJESPENDIENTES
~ {static} String chatATRAS
+ void controlador(ActionListener)
}
class Mensaje {
- String autor
- String destino
- String contenido
- int Identificador
- String fecha
~ DateTimeFormatter dtf
+ void setAutor(String)
+ void setDestino(String)
+ void setContenido(String)
+ void setIdentificador(int)
+ void setFecha(String)
+ String toString()
}
class CtrHorario {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class CtrEnviarMensajesDeveloper {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class Main {
- {static} void createAndShowGui()
+ {static} void main(String[])
}
class Horario {
- String dni
- int[] semana
+ int[] getSemana()
+ String getDni()
+ String toString()
}
class PanelJSolicitudesdeHorario {
- String fuente
~ ConexionBD conex
- JList<String> listaSolicitudes
- DefaultListModel listModel
+ JButton volverAlMenu
~ {static} String bVAM
~ {static} String bAceptar
~ {static} String bDeclinar
~ {static} String seleccionado
- int index
+ void valueChanged(ListSelectionEvent)
+ void controlador(ActionListener)
}
class PanelEnviarMensaje {
~ JButton enviar
~ {static} String bEnviar
~ {static} String bAtras
- JLabel destinatario
- JTextField destinatarioField
- JTextArea mensajeField
~ ConexionBD conex
+ void controlador(ActionListener)
}
class PanelCambiarTelefono {
~ JButton aceptar
~ {static} String bAceptar
~ {static} String bAtras
- JLabel tlfnAnt
- JTextField anttlfn
~ ConexionBD conex
+ void controlador(ActionListener)
}
class CtrConfiguracion {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class PanelCCCorreo {
~ JButton aceptar
~ {static} String bAceptar
~ {static} String bAtras
- JLabel correoAnt
- JTextField antCorreo
~ ConexionBD conex
+ void controlador(ActionListener)
}
class CtrCCFoto {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class PanelRegistro {
- {static} String BT_NEW_USUARIO_ACCION_COMMAND
- JLabel registro
- JTextField nombre
- JPasswordField contrasena
- JButton registrar
~ ConexionBD conex
+ JTextField getNombre()
+ JTextField getApellidos()
+ JTextField getDNI()
+ JTextField getCorreo()
+ JTextField getTelefono()
+ JPasswordField getContrasena()
+ void controlador(CtrlNuevoUsuario)
+ void controlador(ActionListener)
}
class PanelVistaPrincipal {
- JButton Horario
- String fuente
~ {static} String bHorario
~ {static} String bChat
~ {static} String bFichar
~ {static} String bConfiguracion
~ {static} String bHelp
~ {static} String bCS
+ ImagePanel imagenPanel
~ ConexionBD conex
+ void controlador(ActionListener)
+ {static} byte[] toByteArray(BufferedImage,String)
}
class PanelVistaPrincipal.ImagePanel {
- BufferedImage image
~ void setImage(BufferedImage)
# void paintComponent(Graphics)
}
class Empleado {
}
interface VistaEasyJob {
+ void controlador(ActionListener)
}
class PanelSolicitudHorario {
- String fuente
- JButton solicitar
- JLabel ljefe
- JTextField jefe
- JCheckBox lunesMañana
- JCheckBox juevesMañana
~ {static} String bSolicitud
~ {static} String bSAtras
~ ConexionBD conex
+ void controlador(ActionListener)
}
class CtrHelp {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class PanelIniciarSesion {
~ {static} String botonLogin
~ {static} String botonRegistrar
~ {static} String identificador
~ {static} boolean esJefe
- JLabel login
- JTextField dni
- JPasswordField contrasena
- JButton aceptar
~ ConexionBD conex
+ void controlador(ActionListener)
}
abstract class ConexionBD {
~ {static} String JDBC_DRIVER
~ {static} String DB_URL
~ {static} String DB_SCHEMA
~ {static} String USER
~ {static} String PASS
+ {abstract}void introducirUsuario(Usuario)
+ {abstract}boolean buscarUsuario(String,String)
+ {abstract}void eliminarUsuario(String)
+ {abstract}void borrarHorario(String)
+ {abstract}void borrarMensajes(String)
+ {abstract}void borrarSolicitudHorario(String)
+ {abstract}boolean esOnoJefe()
+ {abstract}boolean esOnoJefe(String)
+ {abstract}void cambiarCorreo(String,String,String)
+ {abstract}void cambiarTelefono(String,String,String)
+ {abstract}void cambiarContraseña(String,String,String)
+ {abstract}boolean ContrAntiguaCorrecta(String,String)
+ {abstract}boolean CorreoAntiguoCorrecto(String,String)
+ {abstract}boolean TelefAntiguoCorrecto(String,String)
+ {abstract}Horario horarioFavorito(String)
+ {abstract}List<SolicitudHorario> verSolicitudes()
+ {abstract}void eliminarSolicitud(int)
+ {abstract}void añadirSolicitud(String,int[])
+ {abstract}void cambiarHorario(String,int[])
+ {abstract}List<Usuario> verUsuarios()
+ {abstract}void anadirQR(byte[],String)
+ {abstract}boolean tieneQR(String)
+ {abstract}byte[] getQR(String)
+ {abstract}boolean tieneFoto(String)
+ {abstract}byte[] getFoto(String)
+ {abstract}List<Mensaje> verMensajes()
+ {abstract}List<Mensaje> verMensajesEnviados()
+ {abstract}void EnviarMensaje(String,String,String)
+ {abstract}void BorrarMensaje(int)
+ {abstract}void anadirFoto(byte[],String)
+ {abstract}void Ascender(String,boolean)
+ {abstract}void añadirHorario(String,int[])
}
class PanelVerMensajes {
- String fuente
~ ConexionBD conex
- String[] usuarios
- JList<String> listaMensajes
~ {static} String seleccionado
- int index
- DefaultListModel listModel
~ JButton borrar
~ {static} String bBorrar
~ {static} String bJVE
+ void valueChanged(ListSelectionEvent)
+ void controlador(ActionListener)
}
class PanelConfiguracion {
- String fuente
~ JButton CFoto
~ {static} String bCFoto
~ {static} String bCContraseña
~ {static} String bCCorreo
~ {static} String bCTelefono
~ {static} String bCAtras
+ void controlador(ActionListener)
}
class PanelHorario {
- String fuente
- JButton sHorario
~ {static} String bSHorario
~ {static} String bHAtras
- DefaultListModel listModel
- String[] dias
~ {static} String bFAtras
~ ConexionBD conex
+ void controlador(ActionListener)
}
class CtrJefe {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class CtrCambiarTelefono {
~ VistaEasyJob vistaEasy
+ void actionPerformed(ActionEvent)
}
class SolicitudHorario {
- int iden
- String dni_empleado
- String dni_jefe
- int[] semana
+ int[] getSemana()
+ int getIden()
+ String getDni_empleado()
+ String getDni_jefe()
+ String toString()
}
class CtrEasyJob {
~ VistaEasyJob vistaEasy
~ Usuario usuario
+ void actionPerformed(ActionEvent)
}
class Usuario {
- String Nombre
- String Apellidos
- String CorreoElectronico
- String FotoPerfil
- String DNI
- String Telefono
- String Contrasena
- byte[] QR
- boolean esJefe
+ String toString()
+ String getNombre()
+ void setNombre(String)
+ String getApellidos()
+ void setApellidos(String)
+ String getCorreoElectronico()
+ void setCorreoElectronico(String)
+ String getFotoPerfil()
+ void setFotoPerfil(String)
+ String getDNI()
+ void setDNI(String)
+ String getTelefono()
+ void setTelefono(String)
+ String getContrasena()
+ void setContrasena(String)
+ byte[] getQR()
+ void setQR(byte[])
+ void setEsJefe(boolean)
+ boolean getesJefe()
}
class PanelCCFoto {
~ JButton aceptar
~ {static} String bAceptar
~ {static} String bAtras
- JLabel nuevaFoto
+ ImagePanel imagenPanel
+ BufferedImage img
~ ConexionBD conex
+ void controlador(ActionListener)
+ {static} byte[] toByteArray(BufferedImage,String)
}
class PanelCCFoto.ImagePanel {
- BufferedImage image
~ void setImage(BufferedImage)
# void paintComponent(Graphics)
}


VistaEasyJob <|.. PanelHelp
JPanel <|-- PanelHelp
java.awt.event.ActionListener <|.. CtrChat
java.awt.event.ActionListener <|.. CtrJEmpleados
VistaEasyJob <|.. PanelJefe
JPanel <|-- PanelJefe
PanelJefe +.. PanelJefe.ImagePanel
JPanel <|-- PanelJefe.ImagePanel
VistaEasyJob <|.. PanelCCContraseña
JPanel <|-- PanelCCContraseña
java.awt.event.ActionListener <|.. CtrHSolicitud
java.awt.event.ActionListener <|.. CtrCCContraseña
java.awt.event.ActionListener <|.. CtrCambCorreo
ConexionBD <|-- ConexionBaseDatosJDBC
java.awt.event.ActionListener <|.. CtrlNuevoUsuario
java.awt.event.ActionListener <|.. CtrJSolicitud
java.awt.event.ActionListener <|.. CtrVerMensajes
VistaEasyJob <|.. PanelJVerEmpleados
javax.swing.event.ListSelectionListener <|.. PanelJVerEmpleados
JPanel <|-- PanelJVerEmpleados
VistaEasyJob <|.. PanelEnviarMensajeDeveloper
JPanel <|-- PanelEnviarMensajeDeveloper
java.awt.event.ActionListener <|.. CtrEnviarMensajes
VistaEasyJob <|.. PanelFichar
JPanel <|-- PanelFichar
PanelFichar +.. PanelFichar.ImagePanel
JPanel <|-- PanelFichar.ImagePanel
java.awt.event.ActionListener <|.. CtrFichar
VistaEasyJob <|.. PanelChat
JPanel <|-- PanelChat
java.awt.event.ActionListener <|.. CtrHorario
java.awt.event.ActionListener <|.. CtrEnviarMensajesDeveloper
VistaEasyJob <|.. PanelJSolicitudesdeHorario
javax.swing.event.ListSelectionListener <|.. PanelJSolicitudesdeHorario
JPanel <|-- PanelJSolicitudesdeHorario
VistaEasyJob <|.. PanelEnviarMensaje
JPanel <|-- PanelEnviarMensaje
VistaEasyJob <|.. PanelCambiarTelefono
JPanel <|-- PanelCambiarTelefono
java.awt.event.ActionListener <|.. CtrConfiguracion
VistaEasyJob <|.. PanelCCCorreo
JPanel <|-- PanelCCCorreo
java.awt.event.ActionListener <|.. CtrCCFoto
VistaEasyJob <|.. PanelRegistro
JPanel <|-- PanelRegistro
VistaEasyJob <|.. PanelVistaPrincipal
JPanel <|-- PanelVistaPrincipal
PanelVistaPrincipal +.. PanelVistaPrincipal.ImagePanel
JPanel <|-- PanelVistaPrincipal.ImagePanel
Usuario <|-- Empleado
VistaEasyJob <|.. PanelSolicitudHorario
JPanel <|-- PanelSolicitudHorario
java.awt.event.ActionListener <|.. CtrHelp
VistaEasyJob <|.. PanelIniciarSesion
JPanel <|-- PanelIniciarSesion
VistaEasyJob <|.. PanelVerMensajes
javax.swing.event.ListSelectionListener <|.. PanelVerMensajes
JPanel <|-- PanelVerMensajes
VistaEasyJob <|.. PanelConfiguracion
JPanel <|-- PanelConfiguracion
VistaEasyJob <|.. PanelHorario
JPanel <|-- PanelHorario
java.awt.event.ActionListener <|.. CtrJefe
java.awt.event.ActionListener <|.. CtrCambiarTelefono
java.awt.event.ActionListener <|.. CtrEasyJob
VistaEasyJob <|.. PanelCCFoto
JPanel <|-- PanelCCFoto
PanelCCFoto +.. PanelCCFoto.ImagePanel
JPanel <|-- PanelCCFoto.ImagePanel
@enduml